version: '3'
services:
    mongodb:
      image: mongo
      ports:
        - 8081:8081
  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/code
    links:
    - mongodb
    depends_on:
    - mongodb
  postgresdb:
    image: postgres
    ports:
      - 5555:5432
  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/code
    links:
    - mongodb
    - postgresdb
    depends_on:
    - mongodb
    - postgresdb
  slack_bot:
    build: slack_bot/
    volumes:
    - ./slack_bot/:/code
    depends_on:
    - postgresdb
