version: '3'
services:
  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/code
    links:
    - mongodb
  mongodb:
    image: mongo
    ports:
      - 8081:8081
  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/code
    links:
    - mongodb
    - postgresdb
  postgresdb:
    image: postgres
    ports:
      - 5555:5432
  slack_bot:
    build: slack_bot/
    volumes:
    - ./slack_bot/:/code
